name: flask_project_datacenter
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - alembic==1.13.3
  - blinker==1.8.2
  - cachelib==0.9.0
  - certifi==2024.8.30
  - charset-normalizer==3.4.0
  - click==8.1.7
  - flask==3.0.3
  - flask-caching==2.3.0
  - flask-httpauth==4.8.0
  - flask-jwt-extended==4.6.0
  - flask-migrate==4.0.7
  - flask-sqlalchemy==3.1.1
  - greenlet==3.1.1
  - idna==3.10
  - itsdangerous==2.2.0
  - jinja2==3.1.4
  - mako==1.3.5
  - markupsafe==2.1.5
  - packaging==24.1
  - pymysql==1.1.1
  - python-dateutil==2.9.0.post0
  - python-dotenv==1.0.1
  - pytz==2024.2
  - requests==2.32.3
  - six==1.16.0
  - sqlalchemy==2.0.35
  - typing_extensions==4.12.2
  - tzdata>=2024.1
  - tzlocal==5.2
  - urllib3==2.2.3
  - werkzeug==3.0.4
  - prompt_toolkit==3.0.48
  - wcwidth==0.2.13
  - pip:
      - amqp==5.2.0
      - APScheduler==3.10.4
      - async-timeout==4.0.3
      - billiard==4.2.1
      - celery==5.4.0
      - click-didyoumean==0.3.1
      - click-plugins==1.1.1
      - click-repl==0.3.0
      - cx_Oracle==8.3.0
      - flask-swagger-ui==4.11.1
      - gunicorn==23.0.0
      - kombu==5.4.2
      - PyJWT==2.9.0
      - redis==5.1.0
      - vine==5.1.0
      - websocket-client==1.8.0
      - websockets==13.1
